### ISSUE TITLE
Readme Step 2 What?

### ISSUE THREAD

**Issue by saltedcoffii** [bliutwo/dummy-sound-fix-ubuntu#1]
2. Open the repository in a terminal. in ReadMe.md
Could somebody please elaborate on how to do this?
Thanks.

**Comment by bliutwo** [comment]
Hey sorry, I guess I wasn’t clear. You can right click the folder space in the file explorer equivalent (anywhere that isn’t a file or folder) and click “Open in Terminal”. Does that answer your question?

**Comment by saltedcoffii** [comment]
Sorry it took me so long to respond. Yeah it does.
