### ISSUE TITLE
Kaby Lake support?

### ISSUE THREAD

**Issue by cobalt2727** [bliutwo/dummy-sound-fix-ubuntu#2]
I haven't tried running this on my device yet (HP Chromebook x360 14) since I've put a decent bit of work into my setup already and I don't want to have to restart again, but has this script been tested on Kaby Lake devices? (If not, what's the worst that can happen?)

**Comment by bliutwo** [comment]
I haven't tested this on Kaby Lake, but it might work. I'm not sure what the worst that could happen is, so maybe you could back it up before you try running it.
